org: andr3iii
app: aws-kms-parser-be
service: aws-kms-parser-be
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  environment:
    APP_PORT: ${env:APP_PORT}
    AWS_ACCESS_KEY_IDD: ${env:AWS_ACCESS_KEY_IDD}
    AWS_SECRET_ACCESS_KEYY: ${env:AWS_SECRET_ACCESS_KEYY}
    AWS_REGIONN: ${env:AWS_REGIONN}

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: '{proxy+}'

custom:
  optimize:
    external: ['swagger-ui-dist']
  serverless-offline:
    noPrependStageInUrl: true
